# Generated by Django 5.0.1 on 2024-01-31 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
